name: prod workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  run:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run the prod docker-compose
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URL=https://api.dashboard.yuniq.agency/ >> .env
          echo ENV=prod >> .env
          echo NEXT_PUBLIC_ENVIRONMENT=prod >> .env
          docker-compose up --build -d
