name: rec workflow

on:
  push:
    branches: ["rec"]
  pull_request:
    branches: ["rec"]

  workflow_dispatch:

jobs:
  run:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run the rec docker-compose
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URL=https://api.rec.dashboard.yuniq.agency/ >> .env
          echo ENV=rec >> .env
          echo NEXT_PUBLIC_ENVIRONMENT=rec >> .env
          docker-compose -f docker-compose.rec.yml up --build -d
